avasoft-mobility/cookbook

- src/components/wrapper_components/Text.wrapperComponent.tsx
- src/components/wrapper_components/Text.wrapperComponents.tsx
Implement text wrapper component by using material UI typograph.
- Implemented text wrapper component
- Modified the name of the text component file name from plural to singular
> Implement text wrapper component

- src/components/wrapper_components/CodeBlock.WrapperComponent.tsx
Implemented `CodeBlock` to expose the code and copy that. 
- Created a `CodeBlock` component in `src/components/wrapper_components` folder.
- Implemented `CodeBlock` with code and language as properties.
> Implement codeBlock wrapper component

- src/components/wrapper_components/Pill.WrapperComponent.tsx
Implemented `Pill` to expose the tags for each topics. 
- Created a `Pill` component in `src/components/wrapper_components` folder.
- Implemented `Pill` with label and color as properties.
> Implement Pill wrapper component

- src/components/wrapper_components/Text.wrapperComponent.tsx
Color property is included to the text wrapper component.
- Added color property to text wrapper component
> Include color property to text wrapper component

- src/components/wrapper_components/Icon.WrapperComponent.tsx
- src/components/wrapper_components/KebabMenu.WrapperComponent.tsx
Implemented kebab menu wrapper component by using material UI
- Included new component inside the wrapper folder "KebabMenu.WrapperComponent.tsx"
> Implement kebab menu wrapper component

- src/index.css
Added roboto font dependency and universal style
- Added roboto font dependency and universal style in "index.js file"
> Add roboto font dependency and universal style

- src/components/wrapper_components/DrawerLayout.WrapperComponent.tsx
Implemented drawer layout wrapper component by using material UI
- Included new component inside the wrapper folder "DrawerLayout.WrapperComponent.tsx"
> Add new component drawer layout

- src/components/TopicItem.Component.tsx
Implemented `TopicItem` to expose the short info about the topic. 
- Created a `TopicItem` component in `src/components` folder.
- Implemented `TopicItem` with topic data and custom style is accepts.
- It forms `icons`  with  topic data stack details.
> Implement TopicItem component

- src/components/SideBar.Component.tsx
Implemented `SideBar` as a stack selection menu for a certain topic. 
- Created a `SideBar` component in `src/components` folder.
- Implemented `SideBar` with a array of stack details for a certain topic and which one is selected.
- Created a method `onSelect` with the selected stack.
> Implement SideBar component

- src/dummy-data.json
Dummy json data setup completed
- Included dummy-json data file inside the source folder 
closes #41
> Setup dummy json data

- src/services/ApiService.ts
Included fetchTopics and fetchTopic methods in api service file. The fetchTopics method is to get all topics and searched topic. The fetchtopic method is to get a particular topic
Kindly merge PR #45 before merge this PR.
-Include fetchTopics and fetchTopic methods in api service file
closes #40
> Add fetchTopics and fetchTopic methods

- src/App.tsx
- src/configs/ColorConfig.ts
- src/configs/ThemeConfig.ts
Config Theme and Color 
- Create a ThemeConfig.ts file in Config folder
- Create a ColorConfig.ts file in Config folder
- Config the Theme in App.tsx file
closes #49
> Config Theme and Color

- src/components/TopicItem.Component.tsx
Added Effect for the component.
- Added `Ripple effect` for the component using `material ui`.
closes #51
> Refactor TopicItem component

- src/Pages/DetailsPage.page.tsx
- src/components/MainContent.component.tsx
- src/components/wrapper_components/Accordion.WrapperComponent.tsx
- src/components/wrapper_components/DrawerLayout.WrapperComponent.tsx
Implement DetailsPage in CookbookApp
- Implement The Details Page
- Remove array of objects in MainContent component
- Implement some stylings in other component due to overSpacing
- Image for Details Page
closes #36
> Implement DetailsPage

- src/components/wrapper_components/Accordion.WrapperComponent.tsx
- src/components/wrapper_components/DrawerLayout.WrapperComponent.tsx
Implement Horizontal bar and solve Accordion Error
- Implement Horizontal bar
- Solve Accordion error due to accordion collapse
closes #58
> Implement Horizontal Bar and Solve Accordion Error

- src/services/ApiService.ts
Resolved case sensitivity issue in Api Service fetchTopic method when search
- Converted title to lower case and searched topic to lower case
closes #64
> Resolve case sensitive issue in search method

- src/Pages/Home.page.tsx
- src/components/TopicItem.Component.tsx
- src/components/wrapper_components/Input.WrapperComponent.tsx
Configured Home change and changed color palette.  
- Configure the `Home Screen` with the `ApiService`.
- Exposed a click method for `topicItem`.
- Changed colors from string to `theme palette`.
closes #37
> Configured Home page and Changed Colors

- src/components/wrapper_components/Accordion.WrapperComponent.tsx
- src/components/wrapper_components/AccordionList.WrapperComponent.tsx
Implemented Accordian when to open and close setup
- Added two new props onChange and expanded in Accordian and AccordianList Wrapper component.
- Added one new state expanded in AccordianList Wrapper component
- Added handleAccordianChange function to handle the open and close functionality in AccordianList Wrapper Component
closes #68
> Implement accordian when to open and close setup

- src/Pages/DetailsPage.page.tsx
Changed to menu items link to open on another tab
- Changed navigation method from replace function to open function in Details page.
closes #70
> Change menu links to open on another tab

- src/configs/RouterConfig.tsx
Included root route. when the user enter root url it is navigate to home page
- Added root path to router config file.
closes #71
> Add root route as home page

- src/components/wrapper_components/ConfirmationDialog.WrapperComponent.tsx
- src/components/wrapper_components/ConfirmationDialogRow.WrapperComponent.tsx
Implemented Confirmation Dialogs
- Implement ConfirmationDialogComponent
- Implement ConfirmationDialogRowComponent
closes #80
> Implement ConfirmationDialogs

- src/components/wrapper_components/MultipleSelectChip.WrapperComponent.tsx
Implemented multiple select chip dropdown component
- Created multiple select chip dropdown wrapper component inside the wrapper folder
closes #81
> Create multiple select chip component

- src/components/wrapper_components/ButtonWrapperComponent.tsx
- src/components/wrapper_components/Input.WrapperComponent.tsx
Implement missing functionalities in Button and Input Component
- Implement onclick in ButtonComponenet
- Implement PlaceHolder'sText, value, numberOfLines, inputTextValue in InputComponenet
closes #86
> Add missing functionalities in Button and Input component

- src/Pages/DetailsPage.page.tsx
- src/Pages/Home.page.tsx
- src/components/SideBar.Component.tsx
- src/components/TopicItem.Component.tsx
- src/dummy-data.json
- src/models/Cookbook.Model.ts
- src/models/Stack.Model.ts
- src/models/StackDetails.model.ts
- src/models/Step.Model.ts
- src/models/Tag.Model.ts
- src/models/TimestampedDB.Model.ts
- src/models/TopicDetail.Model.ts
- src/services/ApiService.ts
We have got the EPs now and the model was bit different compared to what we have used to develop. So updating the models and dependent components to adapt new model structure.
- Created `TimestampedDB` to accept `_id`, `createdAt`, `updatedAt` on all models.
- Inherit `TimestampedDB` on all models.
- Removed default data provided to states on all components.
- Removed Stack Detail Component as we don't need them anymore.
Closes #88
> Update models according to EPs

- package-lock.json
- package.json
- src/Pages/DetailsPage.page.tsx
- src/Pages/Home.page.tsx
- src/components/TopicItem.Component.tsx
- src/configs/RouteConfig.ts
- src/dummy-data.json
- src/models/Topic.Model.ts
- src/services/ApiService.ts
- src/services/Client.ts
Home Screen was integrated with Dummy Data before. Now it was configured with real EP and implemented with React Query with debounce.
- Installed use-debounce package.
- Added routes on RouteConfig
- Created HttpClient configured with base url
- Edited the methods on ApiService
- Used react query and debounce to integrate EP on Home Screen.
Closes #90
> Update api service

- src/Pages/DetailsPage.page.tsx
- src/models/Cookbook.Model.ts
- src/services/ApiService.ts
Home Screen was integrated with Dummy Data before. Now it was configured with real EP.
- Used react query to fetch topic data.
- Added `flowchartUrl` and `sampleProjectUrl` on Cookbook Model.
- Mapped the exact values with dummy values.
Closes #91
> Integrate Detail Screen EPs

- src/Pages/Stackpage.page.tsx
- src/components/wrapper_components/ButtonWrapperComponent.tsx
- src/configs/RouterConfig.tsx
- src/models/request_response_models/stack_create.request.model.ts
- src/services/ApiService.ts
- src/services/Client.ts
Implemented add new stack page
- Created new page page in pages folder called "StackPage"
- Modified base URL in client.ts
- Created new method called addStack
- Created request_response_models folder
- Created stack_create.request.model.ts in request_response_models folder
- Added route for stack page and cookbook page
- Added style property in button wrapper component
closes #96
> Implement add new stack page

- src/Pages/CreateTag.page.tsx
- src/configs/RouterConfig.tsx
- src/models/request_response_models/tag_create.request.model.ts
- src/services/ApiService.ts
Implemented create tag page
- Created new page in pages folder called "CreateTag"
- Created new method called addTag
- Created tag_create.request.model.ts in request_response_models folder
- Added route for tag page
closes #105
> Integrate create tag page

- package-lock.json
- package.json
- src/components/Step.Component.tsx
- src/components/StepWrapper.component.tsx
- src/models/StepValue.model.ts
Implement StepComponenet
- Implement Step.component
- Implement StepWrapper.Componenet
- Implement both Component to create multiple create functionalities
- Images of StepWraaper.Componenet
closes #107
> Implement StepComponent

- src/components/SkeletonLoader.Component.tsx
- src/components/TopicItemSkeleton.Component.tsx
- src/components/wrapper_components/Skeleton.WrapperComponent.tsx
- src/configs/ColorConfig.ts
Implemented a skeleton of `TopicItem` for render when fetching data.
- Created `SkeletonLoader` component in `src/components` folder.
- Created `SkeletonWrapper` component in `src/components/wrapper_components` folder.
- Created `TopicItemSkeleton` component in `src/components/wrapper_components` folder.
- Created skeletoncolor in `src/configs/ColorConfig.ts`.
closes #79
> Implement SkeletonLoader Component

- src/App.css
- src/Pages/Home.page.tsx
- src/components/TopicItem.Component.tsx
- src/configs/ThemeConfig.ts
- src/dummy-data.json
- src/services/Client.ts
Configured the Home page as responsive.
- Changed `material UI h3, h4 typography` size in `ThemeConfig`.
- Implemented responsiveness using the `CSS classes` and are exposed in `App.css`.
- Handled the `horizontal scroll bar as overlay` above the content.
- Screen at full width
- Screen takes medium width
- Screen takes small width
closes #75 
closes #77
> Configure responsive homepage

- src/Pages/CreateCookbook.page.tsx
- src/Pages/Topic.Page.tsx
- src/components/wrapper_components/MultipleSelectChip.WrapperComponent.tsx
Implement create navigation for specified pages
- Added create navigation button for cookbook page and topic.
- Added Add stack button on cookbook page
- Added Add topic button on cookbook page
- Added Add tag button on topic page
- Modified multiple select chip component's width from static to "100%" width.
closes #117
> Implement create navigation for specified pages

- package-lock.json
- src/Pages/DetailsPage.page.tsx
- src/components/wrapper_components/AccordionContent.Wrapper.tsx
- src/components/wrapper_components/DrawerLayout.WrapperComponent.tsx
- src/components/wrapper_components/Header.Wrapper.component.tsx
- src/components/wrapper_components/Icon.WrapperComponent.tsx
- src/configs/WindowSize.ts
Implement Responsive Details Page
- Implement sideBarMenu when the page width is reduced to certain value
- Implement SwipeableDrawer when the sideBar menu is clicked
- Decrease the width of the Accordion when the page gets minimised
closes #74
> Implement responsive details page

- src/Pages/CreateStack.page.tsx
- src/Pages/CreateTag.page.tsx
Add width to text input for create stack and tag pages
- Added width to enter stack name text input on create stack page
- Added width to enter tag name text input on create tag page
closes #123
> Include width to text input on stack and tag page

- src/Pages/DetailsPage.page.tsx
- src/components/wrapper_components/DrawerLayout.WrapperComponent.tsx
- src/components/wrapper_components/Header.Wrapper.component.tsx
- src/components/wrapper_components/Icon.WrapperComponent.tsx
- src/configs/WindowSizeConfig.ts
- src/services/Client.ts
Implement Responsive Details Page
- Implement sideBarMenu when the page width is reduced to certain value
- Implement SwipeableDrawer when the sideBar menu is clicked
- Decrease the width of the Accordion when the page gets minimised
closes #74
> Refactor respnsive details page

- src/Pages/Home.page.tsx
- src/components/HomePageMainContent.component.tsx
Integrate loader and no records found message on home page
- Added loader component on home page
- Added no records found message on home page 
closes #125
> Integrate loader and no records message to home page

- src/Pages/CreateStack.page.tsx
- src/Pages/DetailsPage.page.tsx
- src/Pages/Home.page.tsx
- src/Pages/Topic.Page.tsx
Implement ErrorHandling for all Pages except CookBookPage
- Handle Error while Api throws the error
- Use Notistack to display errors
closes #116
> Implement ErrorHandling

- src/Pages/CreateStack.page.tsx
- src/Pages/CreateTag.page.tsx
- src/configs/ColorConfig.ts
Refactor fontWeight and Color
- Refactor fontWeight and Color in CreateStackPage
closes #128
> Refactor fontWeight and Color

- src/Pages/CreateTopic.Page.tsx
- src/configs/RouterConfig.tsx
Changed button size and configured validations in `CreateTopicPage`.
- Changed `save and add new cookbook` button width.
- Implemented `vaildations` for the topic name , tags and fileupload.
closes #130
> Configure validation and buttons in CreateTopic page

- src/Pages/CreateCookbook.page.tsx
- src/Pages/CreateTopic.Page.tsx
- src/hooks/useTabRouter.hook.ts
Created useTabRouter custom hook and replaced the specified navigate function using it. 
- Created new custom hook in the hook folder
- Replaced navigate function using useTabRouter in CreateCookbook page for  Add Topic button 
- Replaced navigate function using useTabRouter in CreateCookbook page for  Add Stack button
- Replaced navigate function using useTabRouter in CreateTopic page for Add Tag button
closes #133
> Create useTabRouter hook and replace specified navigate

- src/components/specified_components/actionable_components/ActionableDropdown.component.tsx
- src/pages/create_pages/CreateCookbook.page.tsx
Separated the dropdown and button with dedicated component  in cookbook page. 
- Created new component `ActionableDropdown` in components folder.
- Replace the dropdown and button logic in the `Cookbook` component page.
closes #135
> Wrap dropdown and button as actionable dropdown component

- package-lock.json
- package.json
- src/components/wrapper_components/AccordionContent.Wrapper.tsx
If the admin adds any links to Cookbook description, it won't be displayed as a hyper link, so making the code descriptions as hyperlinks to access it easily.
- Installed Linkify Package.
- Used that package on AccordionContent component.
Closes #146
> Add linkify support for Cookbook Accordion

- src/components/specified_components/Formik_components/FormikInput.Component.tsx
- src/components/specified_components/steps_components/Step.Component.tsx
- src/components/specified_components/steps_components/StepWrapper.component.tsx
Added custom inputWrapper component inside formik in StepComponent and also changed the formik methodology
- Add custom InputWrapper Component Inside Formik
- Create a new file called `FormikInput` to link the custom inputWrapper component
- Change `Formik` instead of `useFormik`  from formik
closes #145
> Refactor formik in step component

- src/configs/RouterConfig.tsx
- src/models/Author.Model.ts
- src/models/Tag.Model.ts
- src/pages/create_pages/CreateAuthor.page.tsx
- src/pages/create_pages/CreateStack.page.tsx
- src/pages/create_pages/CreateTag.page.tsx
- src/services/ApiService.ts
Implement edit process in Stack, Tag and Author page
- Implement Update Button in all the three pages
- Implement loader while updating in all the three pages
- Save the edited value to the corresponding id
closes #153
> Implement edit process in Stack, Tag and Author page

- src/pages/create_pages/CreateAuthor.page.tsx
- src/pages/create_pages/CreateStack.page.tsx
- src/pages/create_pages/CreateTag.page.tsx
- src/pages/create_pages/CreateTopic.Page.tsx
Changed the headings of each pages.
- If the `queryparam` having `id or slug` the heading changed as update with which page else create. 
closes #165
> Change headings in create pages and button name

- src/components/specified_components/actionable_components/ActionableComboBox.component.tsx
- src/components/specified_components/steps_components/Step.Component.tsx
- src/components/specified_components/steps_components/StepWrapper.component.tsx
- src/components/wrapper_components/ComboBox.WrapperComponent.tsx
- src/configs/RouterConfig.tsx
- src/models/StepValue.model.ts
- src/models/request_response_models/CookbookCreate.request.ts
- src/pages/create_pages/CreateCookbook.page.tsx
- src/services/ApiService.ts
Configured edit functionality for a cookbook page.
- Added an `edit route` to cookbook page
- Added `updateCookbook` and `fetchCookbook` by id methods in Api service
- Added `defaultValue` property to `ActionableComboBox and ComboBoxWrapper` components
- Refactored `Step, StepWrapper and CreateCookbook` components
- Changed `code and image` to optional type in StepValue model
- Added new `author` column in CookbookCreateRequest
closes #166
> Setup update functionality to cookbook page

- src/components/specified_components/detail_page_components/SideBar.Component.tsx
- src/components/wrapper_components/Header.Wrapper.component.tsx
- src/components/wrapper_components/Icon.WrapperComponent.tsx
- src/pages/DetailsPage.page.tsx
Implement Edit Icon in Details Page
- Implement Edit Icon in HeaderComponent
- Implement EditIcon in SideBarComponent
- Navigate to corresponding page when the edit icon gets clicked
closes #163
> Implement Edit Icon in Details Page

- src/models/request_response_models/CookbookCreate.request.ts
- src/pages/create_pages/CreateCookbook.page.tsx
Implement-TechnicalFlow as optional
- Change FlowChartUrl as optional in CookbookCreate model file
- remove the mandatory validations for flowChartUrl in createCookbook page
closes #177
> Implement-TechnicalFlow as optional
